# Site settings
title: IT Trials
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Journal Blog for the trials and errors of a Sysadmin.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://it-trials.github.io" # the base hostname & protocol for your site
github_username:  it-trials

permalink: /:categories/:title.html #simplify url structure

exclude: [Gemfile, Gemfile.lock, README.md, redirect.ps1, docs] # Don't copy these into _site

# Build settings
markdown: kramdown

sass:
  style: compressed

theme: minimal-mistakes-jekyll

minimal_mistakes_skin: "dark"

author: Craig Chamberlain

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      author_profile: true
      layout: single
      read_time: true
      comments: true
      share: true
      related: true

    # _pages
  - scope:
      path: ""
      type: pages
    values:
      author_profile: true
  - scope:
      path: "categories"
      type: pages
    values:
      layout: category
      


comments:
  provider: "disqus"
  disqus:
    shortname: "ittrials"

social:
  type:  # Person or Organization (defaults to Person)
  name:  Craig Chamberlain
  links:
    - "https://twitter.com/hagatorn"
    - "https://www.linkedin.com/in/craig-chamberlain-61037149"
    - "https://stackoverflow.com/users/3822155/craig-c"
    