# Site settings
title: IT Trials
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Journal Blog for the trials and errors of a Sysadmin.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://it-trials.craigchamberlain.it" # the base hostname & protocol for your site
github_username:  it-trials
locale: "en-GB"
og_image: /assets/images/it-trials.jpg
permalink: /:categories/:title #simplify url structure

exclude: [Gemfile, Gemfile.lock, README.md, redirect.ps1, docs, build.sh] # Don't copy these into _site

# Build settings
markdown: kramdown

sass:
  style: compressed

theme: minimal-mistakes-jekyll

plugins:   
  - jekyll-redirect-from

minimal_mistakes_skin: "dark"

author: Craig Chamberlain

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      author_profile: true
      layout: single
      read_time: true
      comments: true
      share: true
      related: true
      show_date: true

    # _pages
  - scope:
      path: ""
      type: pages
    values:
      author_profile: true
  - scope:
      path: "categories"
      type: pages
    values:
      layout: category
      classes: wide

comments:
  provider: "disqus"
  disqus:
    shortname: "ittrials"

social:
  type:  # Person or Organization (defaults to Person)
  name:  Craig Chamberlain
  links:
    - "https://twitter.com/hagatorn"
    - "https://www.linkedin.com/in/craig-chamberlain-61037149"
    - "https://stackoverflow.com/users/3822155/craig-c"
    