# Site settings
title: IT Trials
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Journal Blog for the trials and errors of a Sysadmin.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://it-trials.github.io" # the base hostname & protocol for your site
github_username:  it-trials

permalink: /:categories/:title.html #simplify url structure

exclude: [Gemfile, Gemfile.lock, README.md] # Don't copy these into _site

# Build settings
markdown: kramdown

sass:
  style: compressed

gems: 
  - jekyll-gist
  - jekyll-sitemap
